In [1]:
import numpy as np
import pandas as pd
from numpy import linalg as LA

In [2]:
import sys
sys.path.append('../')
import os
os.path.abspath(os.getcwd())

'/Users/guoyihan/Downloads'

In [3]:
knot_9 = pd.read_csv(r"./data/10000_9_parsed.csv")

In [4]:
knot_9

Unnamed: 0                                braid  \
0              0    [-2, 2, -3, 3, -2, -2, 1, -3, -3]   
1              1    [3, -1, -2, 2, -2, -2, -3, 3, -1]   
2              2        [1, -3, 2, 3, 2, 2, 1, 2, -1]   
3              3    [-1, -1, 1, -1, 3, -2, -1, 3, -2]   
4              4      [1, -3, -2, 3, 1, 1, 2, -1, -3]   
...          ...                                  ...   
9995        9995      [2, 1, -1, 2, -3, 1, -3, 1, -3]   
9996        9996    [-1, 2, -1, 1, -1, 1, -1, -2, -1]   
9997        9997     [1, -3, -1, -3, -2, -3, 2, 2, 3]   
9998        9998     [-2, 2, 3, -2, 3, 2, -1, -2, -3]   
9999        9999  [-2, -1, -2, -2, 2, -3, -1, -1, -2]   

                                              free_part  \
0     {(-11, -4): 1, (-9, -4): 1, (-7, -2): 2, (-5, ...   
1     {(-11, -4): 1, (-9, -4): 1, (-7, -2): 2, (-5, ...   
2          {(1, 0): 1, (3, 0): 1, (5, 2): 1, (9, 3): 1}   
3     {(-11, -4): 1, (-9, -3): 1, (-7, -3): 1, (-7, ...   
4     {(-5, -2): 1, (-3, -2): 1, (-1, 0): 2, (1, 0):...   
...                                                 ...   
9995  {(-7, -3): 1, (-3, -2): 1, (-3, -1): 2, (-1, 0...   
9996  {(-6, -2): 1, (-4, -2): 1, (-2, 0): 1, (0, 0): 1}   
9997     {(-3, 0): 1, (-1, 0): 3, (1, 0): 3, (3, 0): 1}   
9998                            {(-1, 0): 1, (1, 0): 1}   
9999  {(-15, -5): 1, (-11, -4): 1, (-11, -3): 1, (-7...   

                                           torsion_part  total_num_FP  \
0                                                    {}             8   
1                                                    {}             8   
2                                      {(7, 3): {2: 1}}             4   
3     {(-9, -3): {2: 1}, (-7, -2): {2: 1}, (-5, -1):...            12   
4                                                    {}             8   
...                                                 ...           ...   
9995  {(-5, -2): {2: 1}, (-1, 0): {2: 2}, (3, 2): {2...            16   
9996                                                 {}             4   
9997                                                 {}             8   
9998                                                 {}             2   
9999              {(-13, -4): {2: 1}, (-9, -2): {2: 1}}             6   

      total_num_TP                               total_num_FP_per_row  \
0                0        {-11: 1, -9: 1, -7: 2, -5: 2, -3: 1, -1: 1}   
1                0        {-11: 1, -9: 1, -7: 2, -5: 2, -3: 1, -1: 1}   
2                1                           {1: 1, 3: 1, 5: 1, 9: 1}   
3                5  {-11: 1, -9: 1, -7: 2, -5: 2, -3: 2, -1: 3, 3: 1}   
4                0            {-5: 1, -3: 1, -1: 2, 1: 2, 3: 1, 5: 1}   
...            ...                                                ...   
9995             4  {-7: 1, -3: 3, -1: 1, 1: 4, 3: 2, 5: 3, 7: 1, ...   
9996             0                        {-6: 1, -4: 1, -2: 1, 0: 1}   
9997             0                         {-3: 1, -1: 3, 1: 3, 3: 1}   
9998             0                                      {-1: 1, 1: 1}   
9999             2              {-15: 1, -11: 2, -7: 1, -5: 1, -3: 1}   

                             total_num_FP_per_column  
0                               {-4: 2, -2: 4, 0: 2}  
1                               {-4: 2, -2: 4, 0: 2}  
2                                 {0: 2, 2: 1, 3: 1}  
3     {-4: 1, -3: 2, -2: 2, -1: 2, 0: 3, 1: 1, 2: 1}  
4                                {-2: 2, 0: 4, 2: 2}  
...                                              ...  
9995   {-3: 1, -2: 1, -1: 2, 0: 4, 1: 1, 2: 5, 4: 2}  
9996                                   {-2: 2, 0: 2}  
9997                                          {0: 8}  
9998                                          {0: 2}  
9999              {-5: 1, -4: 1, -3: 1, -2: 1, 0: 2}  

[10000 rows x 8 columns]

In [5]:
def J(X,y,v,lambda_):
    ######################### your code goes here ########################
    rowx = len(X)
    J = LA.norm(X@v-y)**2
    re = LA.norm(v,2)**2
    return (1/rowx)*J + lambda_*re

def DJ(X,y,v,lambda_):
    ######################### your code goes here ########################
    rowx = len(X)
    gradient = X.T@X@v-X.T@y
    reg = 2*v
    return (2/rowx)*gradient + lambda_*reg

def GD_linreg_improved(X,y,epsilon,lambda_,max_iters = 10000): 
    ######################### your code goes here ########################
    a = X.shape
    v = np.zeros([a[1],1])
    H = (2/a[0])*X.T@X+2*lambda_*np.identity(a[1])
    costs = [J(X,y,v,lambda_)]
    for i in range(max_iters):
        alpha = (DJ(X,y,v,lambda_).T@DJ(X,y,v,lambda_))/(DJ(X,y,v,lambda_).T@H@DJ(X,y,v,lambda_))
        v = v-DJ(X,y,v,lambda_)*alpha
        costs.append(J(X,y,v,lambda_))
        if i % 1000 == 0:
            print(f'after {i} steps the cost is {costs[i]}')
        if abs(costs[i] - costs[i-1])<epsilon:
            break
    print(f'after {i} steps the cost is {costs[i]}')
    return v,costs

In [6]:
def predict(X,v,y):
    r = np.vectorize(round) 
    X_r = r(X@v)    
    output = [a == p for a,p in zip(y,X_r)]
    count = len([val for val in output if val == True])
    J = LA.norm(X@v-y)**2
    rowx = len(X)
    cost = (1/rowx)*J
    return count,cost

In [7]:
ev = np.vectorize(eval)
row_FP = ev(knot_9["total_num_FP_per_row"])
col_FP = ev(knot_9["total_num_FP_per_column"])

In [8]:
def gen_matrix_row(row_FP):
    row = len(row_FP)
    a = np.empty([row,53])
    for i in range(len(row_FP)):
        for key in row_FP[i].keys():
            a[i,key] =  row_FP[i][key]
        if key == "":
            a[i,key] = 0
    return a

In [9]:
X_row = gen_matrix_row(row_FP)
y = np.array(knot_9['total_num_TP']).reshape(-1,1)

In [10]:
X_train_row = X_row[0:8000]
y_train = y[0:8000]

In [11]:
lambda_ = 0.00001
epsilon = 0.01
v1,costs =  GD_linreg_improved(X_train_row,y_train,epsilon,lambda_) 
print(v1)

after 0 steps the cost is 6.809625
after 18 steps the cost is 1.6936233764301631
[[ 0.09871326]
 [ 0.02798313]
 [ 0.24105843]
 [ 0.5386614 ]
 [ 0.32487852]
 [-0.14392436]
 [ 0.2432971 ]
 [ 0.45160274]
 [ 0.35022339]
 [ 0.67385309]
 [ 0.29106178]
 [ 0.06399245]
 [ 0.21492675]
 [ 0.56588263]
 [ 0.13082945]
 [ 0.3964947 ]
 [ 0.12225396]
 [ 0.2337116 ]
 [ 0.0443274 ]
 [ 0.18058857]
 [ 0.01794849]
 [ 0.09304249]
 [ 0.00804212]
 [ 0.02669449]
 [ 0.        ]
 [ 0.01164239]
 [ 0.        ]
 [ 0.00569146]
 [ 0.00259716]
 [ 0.00247625]
 [ 0.01822523]
 [ 0.01751849]
 [ 0.09662459]
 [ 0.04312473]
 [ 0.17541285]
 [ 0.05147633]
 [ 0.22677704]
 [ 0.11463747]
 [ 0.42759878]
 [ 0.15093888]
 [ 0.59855243]
 [ 0.16945295]
 [ 0.09895819]
 [ 0.27570583]
 [ 0.59848671]
 [ 0.28318552]
 [ 0.29863243]
 [ 0.17978355]
 [-0.10813491]
 [ 0.28327729]
 [ 0.48724776]
 [ 0.22635115]
 [ 0.11076201]]


In [12]:
X_val_row = X_row[8001:9001]
y_val = y[8001:9001]

In [13]:
lambda_ = 0.00001
epsilon = 0.01
v2,costs =  GD_linreg_improved(X_val_row,y_val,epsilon,lambda_,max_iters = 10000)
print(v2)

after 0 steps the cost is 5.6080000000000005
after 19 steps the cost is 1.3995206634483282
[[ 0.17681052]
 [ 0.21759643]
 [ 0.17734632]
 [ 0.40033734]
 [ 0.26286388]
 [-0.13668461]
 [ 0.13513102]
 [ 0.11326958]
 [ 0.18173233]
 [ 0.45766226]
 [ 0.202583  ]
 [ 0.19848056]
 [ 0.10014735]
 [ 0.51477921]
 [ 0.10673041]
 [ 0.39220148]
 [ 0.0537653 ]
 [ 0.35115897]
 [ 0.        ]
 [ 0.21043874]
 [ 0.        ]
 [ 0.13028646]
 [ 0.        ]
 [ 0.06340326]
 [ 0.        ]
 [ 0.02939965]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.01936656]
 [ 0.        ]
 [ 0.03873311]
 [ 0.08027882]
 [ 0.        ]
 [ 0.23411866]
 [ 0.0609068 ]
 [ 0.22376508]
 [ 0.04434738]
 [ 0.61223984]
 [ 0.05596836]
 [ 0.61177409]
 [ 0.07774514]
 [ 0.09355751]
 [ 0.15096184]
 [ 0.76244102]
 [ 0.21773086]
 [ 0.23757361]
 [ 0.18439977]
 [-0.15970791]
 [ 0.25125088]
 [ 0.56342921]
 [ 0.22376212]
 [-0.15743306]]


In [14]:
X_test_row = X_row[9002:10000]
y_test = y[9002:10000]

In [15]:
predict(X_test_row,v2,y_test)

(413, 1.6461033159451914)

In [16]:
def gen_matrix_col(col_FP):
    row = len(col_FP)
    a = np.empty([row,19])
    for i in range(len(col_FP)):
        for key in col_FP[i].keys():
            a[i,key] =  col_FP[i][key]
        if key == "":
            a[i,key] = 0
    return a

In [17]:
X_col = gen_matrix_col(col_FP)

In [18]:
X_train_col = X_col[0:8000]
lambda_ = 0.0001
epsilon = 0.01
v3,costs =  GD_linreg_improved(X_train_col,y_train,epsilon,lambda_) 
print(v3)

after 0 steps the cost is 6.809625
after 17 steps the cost is 0.1376789494467222
[[-0.02320899]
 [ 1.0085032 ]
 [-0.00490006]
 [ 0.99360569]
 [ 0.18743077]
 [ 0.55689057]
 [ 0.25189197]
 [ 0.15561628]
 [ 0.03635778]
 [ 0.01210383]
 [ 0.00216291]
 [ 0.03878908]
 [ 0.1509331 ]
 [ 0.25881655]
 [ 0.55024798]
 [ 0.18944468]
 [ 0.97783909]
 [ 0.00295641]
 [ 0.97190975]]


In [19]:
X_val_col = X_col[8001:9001]
lambda_ = 0.0001
epsilon = 0.01
v4,costs =  GD_linreg_improved(X_val_col,y_val,epsilon,lambda_) 
print(v4)

after 0 steps the cost is 5.6080000000000005
after 19 steps the cost is 0.11959957440494672
[[-0.01855414]
 [ 0.89118037]
 [ 0.00104654]
 [ 0.93537531]
 [ 0.17021848]
 [ 0.50824904]
 [ 0.27949338]
 [ 0.14720443]
 [ 0.08744409]
 [ 0.02279476]
 [ 0.        ]
 [ 0.02563818]
 [ 0.20093868]
 [ 0.3006349 ]
 [ 0.63604098]
 [ 0.15714837]
 [ 1.00515647]
 [-0.00445581]
 [ 1.01844133]]


In [20]:
X_test_col = X_col[9002:10000]

In [21]:
predict(X_test_col,v3,y_test)

(926, 0.09621027675507988)